"""added verification token

Revision ID: 4bb9a72aaf2b
Revises: 5b4b97668f49
Create Date: 2025-06-20 01:53:06.067323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb9a72aaf2b'
down_revision = '5b4b97668f49'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ndc_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade_ndc_users():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###


def upgrade_ndc_sheets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ndc_sheets():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

