"""initial migration

Revision ID: af9c69fcde80
Revises: 
Create Date: 2025-06-21 22:09:12.444365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9c69fcde80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.LargeBinary(), nullable=False),
    sa.Column('email_hash', sa.LargeBinary(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('pref_lang', sa.String(length=2), nullable=False),
    sa.Column('flags', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_hash')
    )
    op.create_table('sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=64), nullable=False),
    sa.Column('light_condition', sa.SmallInteger(), nullable=False),
    sa.Column('quality', sa.SmallInteger(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_name')
    )
    op.create_table('verification_tokens',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_tokens')
    op.drop_table('sheets')
    op.drop_table('users')
    # ### end Alembic commands ###
